import { Router } from "express";
import { DoctorApplicationRoutes } from "../module/doctorApplication/doctorApplication.route";
import { AdminRoutes } from "../module/admin/admin.route";
import { AppointmentRoutes } from "../module/appointment/appointment.route";
import { AuthRoutes } from "../module/auth/auth.route";
import { CallRoutes } from "../module/call/call.route";
import { ChatRoutes } from "../module/chat/chat.route";
import { DoctorRoutes } from "../module/doctor/doctor.route";
import { DoctorScheduleRoutes } from "../module/doctorSchedule/doctorSchedule.route";
import { MedicalRecordRoutes } from "../module/medicalRecord/medicalRecord.route";
import { NotificationRoutes } from "../module/notification/notification.route";
import { PatientRoutes } from "../module/patient/patient.route";
import { PaymentRoutes } from "../module/payment/payment.route";
import { PrescriptionRoutes } from "../module/prescription/prescription.route";
import { scheduleRoutes } from "../module/schedule/schedule.route";
import { SpecialtyRoutes } from "../module/specialty/specialty.route";
import { ServiceRoutes } from "../module/service/service.route";
import { UserRoutes } from "../module/user/user.route";

const router = Router();

router.use("/auth", AuthRoutes);
router.use("/specialties", SpecialtyRoutes);
router.use("/services", ServiceRoutes);
router.use("/users", UserRoutes);
router.use("/patients", PatientRoutes);
router.use("/doctors", DoctorRoutes);
router.use("/admins", AdminRoutes);
router.use("/schedules", scheduleRoutes);
router.use("/doctor-schedules", DoctorScheduleRoutes);
router.use("/appointments", AppointmentRoutes);
router.use("/medical-records", MedicalRecordRoutes);
router.use("/prescriptions", PrescriptionRoutes);
router.use("/payments", PaymentRoutes);
router.use("/notifications", NotificationRoutes);
router.use("/chat", ChatRoutes);
router.use("/calls", CallRoutes);
router.use("/doctor-applications", DoctorApplicationRoutes);

export const IndexRoutes = router;
